CC = gcc 
SRC1 = src/exo1.c
SRC2 = src/exo2.c
SRC3 = src/exo3.c

CFLAGS = -Wall 

BIN = main

exo1 : $(SRC1)
	$(CC) $(CFLAGS) $^ -o $(BIN) 

exo2 : $(SRC2)
	$(CC) $(CFLAGS) $^ -o $(BIN)

exo3 : $(SRC3)
	$(CC) $(CFLAGS) $^ -o $(BIN)


